defaults:
  - _self_
  - data: template
  - model: template

seed: 42
max_epochs: 10
accelerator: "auto"
devices: "auto"

wandb:
  mode: "online" # Options: online, offline, disabled

# Hydra settings
hydra:
  run:
    dir: logs/${data.name}/${model.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${data.name}/${model.name}/${hydra.job.num}