defaults:
  - _self_
  - data: template
  - model: template

seed: 42
max_epochs: 10
accelerator: "auto"
devices: "auto"
resume: null

wandb:
  mode: "online" # Options: online, offline, disabled

# Hydra settings
hydra:
  run:
    dir: ${resolve_run_dir:${resume},${data.name},${model.name}}
  sweep:
    dir: ${resolve_sweep_dir:${resume}}
    subdir: ${data.name}/${model.name}/${hydra.job.num}